language: cpp

sudo: required


services:
- docker

env:
  matrix:
    - DISTRO=ubuntu_mpi BUILD_TYPE=Debug DOCKERHUB=true
   # - DISTRO=fedora_mpi BUILD_TYPE=Release DOCKERHUB=true

before_install:
 - git fetch --unshallow && git fetch --tags #for versioning

script:
  - pwd
  - ls
  - if [[ ${CC} != gcc ]]; then TAG="_${CC}"; fi
  - if [[ ${TRAVIS_BRANCH} != stable ]]; then TAG="${TAG}_master"; fi
  - cp -vr docker ${HOME}/docker
  - sed -i "1s/fedora_serial/${DISTRO}${TAG}/" ${HOME}/docker/Dockerfile
  - cd ../../
  - cp -r ${TRAVIS_REPO_SLUG} $HOME/docker
 # - docker build --build-arg BUILD_TYPE=${BUILD_TYPE} 
 #               --build-arg CC=${CC} --build-arg CXX=${CXX}
 #               --build-arg CI=${CI} --build-arg TRAVIS=${TRAVIS} --build-arg TRAVIS_OS_NAME=${DISTRO}
 #               --build-arg TRAVIS_BRANCH=${TRAVIS_BRANCH} --build-arg TRAVIS_JOB_NUMBER=${TRAVIS_JOB_NUMBER}
 #               --build-arg TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST} --build-arg TRAVIS_JOB_ID=${TRAVIS_JOB_ID}
 #               --build-arg TRAVIS_TAG=${TRAVIS_TAG} --build-arg TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
 #               --build-arg TRAVIS_COMMIT=${TRAVIS_COMMIT}
 #               -t ${TRAVIS_REPO_SLUG}:${DISTRO}${TAG} ${HOME}/docker/ &&
 #   CON=$(docker run -d ${TRAVIS_REPO_SLUG}:${DISTRO}${TAG} /bin/bash)

after_success:
 # - if [[ ${DOCKERHUB} = true && ${DOCKER_USERNAME} && ${DOCKER_PASSWORD} && ${TRAVIS_PULL_REQUEST} == false && ${TRAVIS_BRANCH} == master && ${CC} = gcc ]]; then
 #     docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
 #     docker push "${TRAVIS_REPO_SLUG}:${DISTRO}${TAG}";
 #   fi
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - cd ${HOME}/build/${TRAVIS_REPO_SLUG}
  - git checkout ${TRAVIS_BRANCH}
  
  
  
  - cd ${HOME}
  - git clone https://${GH_TOKEN}@github.com/lanl/BEE_Private.git && cd ./BEE_Private
  - git checkout beeswarm-enhancement
  - ./install_on_travis.sh
  #- source ${HOME}/build/${TRAVIS_REPO_SLUG}/bee_scalability_test/CH-819321-openrc.sh
  #- env
  - export PATH=$(pwd)/bee-launcher:$PATH
  #- export PATH=$(pwd)/travis_ci:$PATH
  - export PATH=${HOME}/build/${TRAVIS_REPO_SLUG}/bee_scalability_test:$PATH
  #- echo $PATH
  
  - cd ${HOME}/build/${TRAVIS_REPO_SLUG}/bee_scalability_test
  #- travis_wait 120 bee_ci_launcher.py -l flecsale -r $OS_RESERVATION_ID
  #- ls
  #- output_parser.py
  
  #- cp bee_scalability_test_parsed.output ${HOME}/build/${TRAVIS_REPO_SLUG}/bee_scalability_test/bee_scalability_test_result_build_${TRAVIS_BUILD_NUMBER}.csv
  - touch ${HOME}/build/${TRAVIS_REPO_SLUG}/bee_scalability_test/bee_scalability_test_result_build_${TRAVIS_BUILD_NUMBER}.csv
  #- mv bee_scalability_test_result_build_${TRAVIS_BUILD_NUMBER}.csv ${HOME}/build/${TRAVIS_REPO_SLUG}/bee_scalability_test
  #- push_results_to_repo.sh
  - git add bee_scalability_test_result_build_${TRAVIS_BUILD_NUMBER}.csv
  - git commit --message "[skip ci]"
  - git remote add remote_repo https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  - git push remote_repo ${TRAVIS_BRANCH} 
  
compiler:
  - gcc

